create database clinica;
use clinica;

-- TIPO ATENDIMENTO
create table TIAT(
TIAT_ID int auto_increment PRIMARY KEY,
TIAT_DS CHAR(30)
);

-- DEPARTAMENTO
create table DEPA(
DEPA_ID int auto_increment PRIMARY KEY,
DEPA_DS CHAR(30),
DEPA_ST CHAR(10)
);

-- TIDO DE DOCUMENTO
create table TIDO(
TIDO_ID int auto_increment PRIMARY KEY,
TIDO_DS CHAR(30)
);

-- TIDO DE CONTATO
create table TICO(
TICO_ID int auto_increment PRIMARY KEY,
TICO_DS CHAR(30)
);

-- PACIENTE
create table PACI(
PACI_ID int auto_increment PRIMARY KEY,
PACI_NM CHAR(30),
PACI_NS DATE NOT NULL,
PACI_CD DATE
);

-- FUNÇÃO
create table FUNC(
FUNC_ID INT NOT NULL PRIMARY KEY,
FUNC_DS CHAR(30),
FUNC_ST CHAR(10)
);

-- CONTATO
create table CONT(
CONT_ID INT NOT NULL PRIMARY KEY,
CONT_DS CHAR(30),
CONT_CM VARCHAR(100),
FK_TICO_CONT_ID int,
FK_PACI_CONT_ID int,
FOREIGN KEY (FK_TICO_CONT_ID) REFERENCES TICO (TICO_ID),
FOREIGN KEY (FK_PACI_CONT_ID) REFERENCES PACI (PACI_ID)
);

-- DOCUMENTO
create table DOCU(
DOCU_NM INT NOT NULL PRIMARY KEY,
DOCU_CM VARCHAR(100),
DOCU_EM DATE NOT NULL,
FK_TIDO_DOCU_ID int,
FK_PACI_DOCU_ID int,
FOREIGN KEY (FK_TIDO_DOCU_ID) REFERENCES TIDO (TIDO_ID),
FOREIGN KEY (FK_PACI_DOCU_ID) REFERENCES PACI (PACI_ID)
);

-- PROFISSIONAL
create table PROF(
PROF_ID int auto_increment PRIMARY KEY,
PROF_ST CHAR(10),
PROF_NM VARCHAR(50),
PROF_NS DATE,
FK_DEPA_PROF_ID int,
FK_FUNC_PROF_ID int,
FOREIGN KEY (FK_DEPA_PROF_ID) REFERENCES DEPA (DEPA_ID),
FOREIGN KEY (FK_FUNC_PROF_ID) REFERENCES FUNC (FUNC_ID)
);

-- ATENDIMENTO
create table ATEN(
ATEN_ID int auto_increment PRIMARY KEY,
ATEN_DT DATE NOT NULL,
ATEN_PS INT,
ATEN_AL INT,
FK_TIAT_ATEN_ID int,
FK_PROF_ATEN_ID int,
FK_PACI_ATEN_ID int,
FOREIGN KEY (FK_TIAT_ATEN_ID) REFERENCES TIAT (TIAT_ID),
FOREIGN KEY (FK_PROF_ATEN_ID) REFERENCES PROF (PROF_ID),
FOREIGN KEY (FK_PACI_ATEN_ID) REFERENCES PACI (PACI_ID)
);

-- EQUIPE
create table EQUI(
FK_PROF_EQUI_ID int,
FK_ATEN_EQUI_ID int,
FOREIGN KEY (FK_PROF_EQUI_ID) REFERENCES PROF (PROF_ID),
FOREIGN KEY (FK_ATEN_EQUI_ID) REFERENCES ATEN (ATEN_ID)
);



