-- GU 3030768

create database clinica;
use clinica;


-- TIPO ATENDIMENTO
create table TI_ATENDIMENTO(
TIAT_ID int auto_increment PRIMARY KEY,
TIAT_DS CHAR(30)
);

-- DEPARTAMENTO
create table DEPARTAMENTO(
DEPA_ID int auto_increment PRIMARY KEY,
DEPA_DS CHAR(30),
DEPA_ST CHAR(10)
);

-- TIPO DE DOCUMENTO
create table TI_DOCUMENTO(
TIDO_ID int auto_increment PRIMARY KEY,
TIDO_DS CHAR(30)
);

-- TIPO DE CONTATO
create table TI_CONTATO(
TICO_ID int auto_increment PRIMARY KEY,
TICO_DS CHAR(30)
);

-- PACIENTE
create table PACIENTE(
PACI_ID int auto_increment PRIMARY KEY,
PACI_NM CHAR(30),
PACI_NS DATE NOT NULL,
PACI_CD DATE
);

-- FUNÇÃO
create table FUNCAO(
FUNC_ID INT auto_increment PRIMARY KEY,
FUNC_DS CHAR(30),
FUNC_ST CHAR(10)
);

-- CONTATO
create table CONTATO(
CONT_ID INT auto_increment PRIMARY KEY,
CONT_DS CHAR(30),
CONT_CM VARCHAR(100),
TICO_CONT_ID int,
PACI_CONT_ID int,
constraint FK_TICO_CONT_ID FOREIGN KEY (TICO_CONT_ID) REFERENCES TI_CONTATO (TICO_ID),
constraint FK_PACI_CONT_ID FOREIGN KEY (PACI_CONT_ID) REFERENCES PACIENTE (PACI_ID)
);

-- DOCUMENTO
create table DOCUMENTO(
DOCU_NM INT auto_increment PRIMARY KEY,
DOCU_CM VARCHAR(100),
DOCU_EM DATE NOT NULL,
TIDO_DOCU_ID int,
PACI_DOCU_ID int,
constraint FK_TIDO_DOCU_ID FOREIGN KEY (TIDO_DOCU_ID) REFERENCES TI_DOCUMENTO (TIDO_ID),
constraint FK_PACI_DOCU_ID FOREIGN KEY (PACI_DOCU_ID) REFERENCES PACIENTE (PACI_ID)
);

-- PROFISSIONAL
create table PROFISSIONAL(
PROF_ID int auto_increment PRIMARY KEY,
PROF_ST CHAR(10),
PROF_NM VARCHAR(50),
PROF_NS DATE NOT NULL,
DEPA_PROF_ID int,
FUNC_PROF_ID int,
constraint FK_DEPA_PROF_ID FOREIGN KEY (DEPA_PROF_ID) REFERENCES DEPARTAMENTO (DEPA_ID),
constraint FK_FUNC_PROF_ID FOREIGN KEY (FUNC_PROF_ID) REFERENCES FUNCAO (FUNC_ID)
);

-- ATENDIMENTO
create table ATENDIMENTO(
ATEN_ID int auto_increment PRIMARY KEY,
ATEN_DT DATE NOT NULL,
ATEN_PS INT,
ATEN_AL INT,
TIAT_ATEN_ID int,
PROF_ATEN_ID int,
PACI_ATEN_ID int,
constraint FK_TIAT_ATEN_ID FOREIGN KEY (TIAT_ATEN_ID) REFERENCES TI_ATENDIMENTO (TIAT_ID),
constraint FK_PROF_ATEN_ID FOREIGN KEY (PROF_ATEN_ID) REFERENCES PROFISSIONAL (PROF_ID),
constraint FK_PACI_ATEN_ID FOREIGN KEY (PACI_ATEN_ID) REFERENCES PACIENTE (PACI_ID)
);

-- EQUIPE
create table EQUIPE(
PROF_EQUI_ID int,
ATEN_EQUI_ID int,
constraint FK_PROF_EQUI_ID FOREIGN KEY (PROF_EQUI_ID) REFERENCES PROFISSIONAL (PROF_ID),
constraint FK_ATEN_EQUI_ID FOREIGN KEY (ATEN_EQUI_ID) REFERENCES ATENDIMENTO (ATEN_ID)
);



